pipeline {
    agent {
        docker {
	/*
            image 'maven:3-alpine'
	    */
            image 'kockopes/builder-java:2.0.0'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
