pipeline {
    agent {
        docker {
	/*
            image 'maven:3-alpine'
	    */
            image 'kockopes/builder-java:1.0.0'
	    /*
	    args '-v /var/run/docker.sock:/var/run/docker.sock'
	    */
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
